### PR TITLE
Homeowrk week2 React Mohammad-SD

### PR DESCRIPTION
**Pull request by mosaadaldeen**

### CODE REVIEW

**Comment by mosaadaldeen** [comment]
Link to the project [here](hacktheweather.netlify.app)

**Comment by mosaadaldeen** [comment]
Link to the project: hacktheweather.netlify.app

**Comment by mosaadaldeen** [comment]
I have a problem with git, so I have worked on the project in a separated repository, here is the link:
[here](https://github.com/mosaadaldeen/HackYourWeather)

**Comment by mosaadaldeen** [comment]
I've added another src folder in the same react app of the homework because I still have a problem in git.

**Comment by Tjebbee** [comment]
Please join Noer's tech hour if you are facing difficulties!

**Pull request closed without merging**
